from ListasDoblementeLigadas import DoubleLinkedList

f = DoubleLinkedList()
print(f"¿La lista esta vacia? {f.is_empty()}")
f.append(2)
f.append(4)
f.append(6)
f.append(8)
f.append(10)
f.append(12)
f.append(14)
f.append(16)
f.append(18)
f.append(20)
f.transversal()
print(f"¿La lista esta vacia? {f.is_empty()}")
f.get_size()
f.reverse_transversal()
f.find_from_tail(2)
f.find_from_head(8)
f.remove_from_tail(8)
f.transversal()
f.remove_from_head(4)
f.transversal()
